# Run flutter analyze and test for every PR
name: development

# run on every PR and every push
on:
  push:
    branches: 
      - development
  pull_request:
    branches: 
      - development

  workflow_dispatch:

jobs:
  flutter_check:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: Get packages
        run: flutter pub get
      
      - name: Analyze
        run: flutter analyze
      
      - name: Test
        run: flutter test